### ISSUE TITLE
Only file deleted commit failed

### ISSUE THREAD

**Issue by GooBitGitKome** [Gonsix/Code-Agent#2]
Hello. Thank you for all of your help.
I met an error again. This was that I could not execute`codex gen-commit` for the commit of only deleting some files. 

The flow what I did: After installing and set the environment variable. Then I tried to `codex gen-commit` after `git add .`(I already did the first commit some datas).

The error message:

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc7 in position 31: invalid continuation byte

**Comment by Gonsix** [comment]
@GooBitGitKome 
Hi, I tried replaying what you did but I couldn't met the error. I succeeded  `codex gen-commit` command with only deleted files.
<img width="1470" alt="スクリーンショット 2024-03-12 15 22 45" src="https://github.com/Gonsix/Code-Agent/assets/105830364/132a47ab-7dad-45b6-bbe1-8237bd86e0d4">

From the error message you provided, you seem to given strange files for input. 
For more help, please show me more informative description and  entire error message.

**Comment by GooBitGitKome** [comment]
Sorry, the error message included the personal paths, so I left out those. 
As you said, I deleted not code files but pdf files. I should've told you that first. If you need whole of the error code, I will send you in another way.

**Comment by Gonsix** [comment]
Close as it was improper input.
